/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backgammon;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.red;
import java.awt.Graphics;
import java.awt.Polygon;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Random;
import java.util.Stack;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        initComponents();
        Board obj = new Board();
        obj.tablaBoard();
        //roll.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        field13 = new javax.swing.JPanel();
        field12 = new javax.swing.JPanel();
        field11 = new javax.swing.JPanel();
        field10 = new javax.swing.JPanel();
        field9 = new javax.swing.JPanel();
        field7 = new javax.swing.JPanel();
        field6 = new javax.swing.JPanel();
        field5 = new javax.swing.JPanel();
        field4 = new javax.swing.JPanel();
        field3 = new javax.swing.JPanel();
        field2 = new javax.swing.JPanel();
        field1 = new javax.swing.JPanel();
        field14 = new javax.swing.JPanel();
        field15 = new javax.swing.JPanel();
        field16 = new javax.swing.JPanel();
        field17 = new javax.swing.JPanel();
        field18 = new javax.swing.JPanel();
        field19 = new javax.swing.JPanel();
        field20 = new javax.swing.JPanel();
        field21 = new javax.swing.JPanel();
        field22 = new javax.swing.JPanel();
        field23 = new javax.swing.JPanel();
        field24 = new javax.swing.JPanel();
        field25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        photo2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        photo3 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        roll = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 173));

        field13.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field13Layout = new javax.swing.GroupLayout(field13);
        field13.setLayout(field13Layout);
        field13Layout.setHorizontalGroup(
            field13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field13Layout.setVerticalGroup(
            field13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field12.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field12Layout = new javax.swing.GroupLayout(field12);
        field12.setLayout(field12Layout);
        field12Layout.setHorizontalGroup(
            field12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field12Layout.setVerticalGroup(
            field12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        field11.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field11Layout = new javax.swing.GroupLayout(field11);
        field11.setLayout(field11Layout);
        field11Layout.setHorizontalGroup(
            field11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field11Layout.setVerticalGroup(
            field11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field10.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field10Layout = new javax.swing.GroupLayout(field10);
        field10.setLayout(field10Layout);
        field10Layout.setHorizontalGroup(
            field10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field10Layout.setVerticalGroup(
            field10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field9.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field9Layout = new javax.swing.GroupLayout(field9);
        field9.setLayout(field9Layout);
        field9Layout.setHorizontalGroup(
            field9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field9Layout.setVerticalGroup(
            field9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field7.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field7Layout = new javax.swing.GroupLayout(field7);
        field7.setLayout(field7Layout);
        field7Layout.setHorizontalGroup(
            field7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field7Layout.setVerticalGroup(
            field7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field6.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field6Layout = new javax.swing.GroupLayout(field6);
        field6.setLayout(field6Layout);
        field6Layout.setHorizontalGroup(
            field6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field6Layout.setVerticalGroup(
            field6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field5.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field5Layout = new javax.swing.GroupLayout(field5);
        field5.setLayout(field5Layout);
        field5Layout.setHorizontalGroup(
            field5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field5Layout.setVerticalGroup(
            field5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field4.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field4Layout = new javax.swing.GroupLayout(field4);
        field4.setLayout(field4Layout);
        field4Layout.setHorizontalGroup(
            field4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field4Layout.setVerticalGroup(
            field4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        field3.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field3Layout = new javax.swing.GroupLayout(field3);
        field3.setLayout(field3Layout);
        field3Layout.setHorizontalGroup(
            field3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field3Layout.setVerticalGroup(
            field3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field2.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field2Layout = new javax.swing.GroupLayout(field2);
        field2.setLayout(field2Layout);
        field2Layout.setHorizontalGroup(
            field2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field2Layout.setVerticalGroup(
            field2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field1.setBackground(new java.awt.Color(255, 222, 173));
        field1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                field1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout field1Layout = new javax.swing.GroupLayout(field1);
        field1.setLayout(field1Layout);
        field1Layout.setHorizontalGroup(
            field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field1Layout.setVerticalGroup(
            field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        field14.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field14Layout = new javax.swing.GroupLayout(field14);
        field14.setLayout(field14Layout);
        field14Layout.setHorizontalGroup(
            field14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field14Layout.setVerticalGroup(
            field14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field15.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field15Layout = new javax.swing.GroupLayout(field15);
        field15.setLayout(field15Layout);
        field15Layout.setHorizontalGroup(
            field15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field15Layout.setVerticalGroup(
            field15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field16.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field16Layout = new javax.swing.GroupLayout(field16);
        field16.setLayout(field16Layout);
        field16Layout.setHorizontalGroup(
            field16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field16Layout.setVerticalGroup(
            field16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field17.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field17Layout = new javax.swing.GroupLayout(field17);
        field17.setLayout(field17Layout);
        field17Layout.setHorizontalGroup(
            field17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field17Layout.setVerticalGroup(
            field17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field18.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field18Layout = new javax.swing.GroupLayout(field18);
        field18.setLayout(field18Layout);
        field18Layout.setHorizontalGroup(
            field18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field18Layout.setVerticalGroup(
            field18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field19.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field19Layout = new javax.swing.GroupLayout(field19);
        field19.setLayout(field19Layout);
        field19Layout.setHorizontalGroup(
            field19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field19Layout.setVerticalGroup(
            field19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field20.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field20Layout = new javax.swing.GroupLayout(field20);
        field20.setLayout(field20Layout);
        field20Layout.setHorizontalGroup(
            field20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field20Layout.setVerticalGroup(
            field20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field21.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field21Layout = new javax.swing.GroupLayout(field21);
        field21.setLayout(field21Layout);
        field21Layout.setHorizontalGroup(
            field21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field21Layout.setVerticalGroup(
            field21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field22.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field22Layout = new javax.swing.GroupLayout(field22);
        field22.setLayout(field22Layout);
        field22Layout.setHorizontalGroup(
            field22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field22Layout.setVerticalGroup(
            field22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field23.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field23Layout = new javax.swing.GroupLayout(field23);
        field23.setLayout(field23Layout);
        field23Layout.setHorizontalGroup(
            field23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field23Layout.setVerticalGroup(
            field23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field24.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field24Layout = new javax.swing.GroupLayout(field24);
        field24.setLayout(field24Layout);
        field24Layout.setHorizontalGroup(
            field24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field24Layout.setVerticalGroup(
            field24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        field25.setBackground(new java.awt.Color(255, 222, 173));

        javax.swing.GroupLayout field25Layout = new javax.swing.GroupLayout(field25);
        field25.setLayout(field25Layout);
        field25Layout.setHorizontalGroup(
            field25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        field25Layout.setVerticalGroup(
            field25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jPanel26.setBackground(new java.awt.Color(255, 222, 173));
        jPanel26.setEnabled(false);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(255, 222, 173));
        jButton1.setText("Start game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel27.setBackground(new java.awt.Color(255, 222, 173));

        roll.setBackground(new java.awt.Color(255, 222, 173));
        roll.setText("Roll dice");
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(roll)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jButton2.setText("End turn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(field14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(field13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(photo3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(field6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(photo2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jButton2))
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(field20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(field21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(field22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(field23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(field24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(field25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(field12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(field4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(photo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(photo3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(field25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        jPanel27.setVisible(true);
//jPanel26.setVisible(true);
        //roll.setVisible(true);
        //jPanel26.setVisible(true);
Graphics g = field13.getGraphics();
        int x = field13.getWidth();
        int y = field13.getHeight();
        int[] x1 = new int[]{0, x / 2, x};
        int[] y1 = new int[]{0, y, 0};
        Polygon p1 = new Polygon(x1, y1, 3);     
        g.setColor(new Color(65, 42, 42));
        g.drawPolygon(p1);
        g.fillPolygon(p1);
        g.setColor(black);
        for(int i=0;i<5;i++){
            g.drawOval(10,0+i*50, 50, 50);
            g.fillOval(10,0+i*50,50,50);
        }
        Graphics g1 = field12.getGraphics();
        g1.setColor(new Color(255, 250, 250));
        g1.fillPolygon(p1);
        Graphics g2 = field11.getGraphics();
        g2.setColor(new Color(65, 42, 42));
        g2.drawPolygon(p1);
        g2.fillPolygon(p1);
        Graphics g3 = field10.getGraphics();
        g3.setColor(new Color(255, 250, 250));
        g3.drawPolygon(p1);
        g3.setColor(new Color(255, 250, 250));
        g3.fillPolygon(p1);
        Graphics g4 = field9.getGraphics();
        g4.setColor(new Color(65, 42, 42));
        g4.drawPolygon(p1);
        g4.fillPolygon(p1);
        g4.setColor(new Color(255,0,0));
        for(int i=0;i<3;i++){
            g4.drawOval(10,0+i*50,50,50);
             g4.fillOval(10,0+i*50,50,50);
        }
        Graphics g5 = field7.getGraphics();
        g5.setColor(new Color(255, 250, 250));
        g5.drawPolygon(p1);
        g5.fillPolygon(p1);
        Graphics g6 = field6.getGraphics();
        g6.setColor(new Color(65, 42, 42));
        g6.drawPolygon(p1);
        g6.fillPolygon(p1);
         g6.setColor(new Color(255,0,0));
         for(int i=0;i<5;i++){
             g6.drawOval(10,0+i*50,50,50);
             g6.fillOval(10,0+i*50,50,50);
         }
        Graphics g7 = field5.getGraphics();
        g7.setColor(new Color(255, 250, 250));
        g7.drawPolygon(p1);
        g7.fillPolygon(p1);
        Graphics g8 = field4.getGraphics();
        g8.drawPolygon(p1);
        g8.setColor(new Color(65, 42, 42));
        g8.fillPolygon(p1);
        Graphics g9 = field3.getGraphics();
        g9.setColor(new Color(255, 250, 250));
        g9.drawPolygon(p1);
        g9.fillPolygon(p1);
        Graphics g10 = field2.getGraphics();
        g10.setColor(new Color(65, 42, 42));
        g10.drawPolygon(p1);
        g10.fillPolygon(p1);
        Graphics g11 = field1.getGraphics();
        g11.setColor(new Color(255, 250, 250));
        g11.drawPolygon(x1, y1, 3);
        g11.fillPolygon(p1);
        g11.setColor(black);
        for(int i=0;i<2;i++){
        g11.drawOval(10, 0+i*50, 50, 50);
        g11.fillOval(10,0+i*50,50,50);
        }
        
        int x2[] = new int[]{0, x / 2, x};
        int y2[] = new int[]{y - 4, 0, y - 4};
        Polygon p = new Polygon(x2, y2, 3);
        Graphics g12 = field14.getGraphics();
        g12.setColor(new Color(255, 250, 250));
        g12.drawPolygon(p);
        g12.fillPolygon(p);
         g12.setColor(new Color(255,0,0));
         for(int i=0;i<5;i++){
        g12.drawOval(10, 0+i*50, 50, 50);
        g12.fillOval(10,0+i*50,50,50);
         }
        Graphics g13 = field15.getGraphics();
        g13.setColor(new Color(65, 42, 42));
        g13.drawPolygon(p);
        g13.fillPolygon(p);
        Graphics g14 = field16.getGraphics();
        g14.setColor(new Color(255, 250, 250));
        g14.drawPolygon(p);   
        g14.fillPolygon(p);
        Graphics g15 = field17.getGraphics();
        g15.setColor(new Color(65, 42, 42));
        g15.drawPolygon(p);     
        g15.fillPolygon(p);
        Graphics g16 = field18.getGraphics();
        g16.setColor(new Color(255, 250, 250));
        g16.drawPolygon(p);       
        g16.fillPolygon(p);
        g16.setColor(black);
        for(int i=1;i<4;i++){
        g16.drawOval(10, y-50*i, 50, 50);
        g16.fillOval(10,y-50*i,50,50);
        }    
        Graphics g17 = field19.getGraphics();
        g17.setColor(new Color(65, 42, 42));
        g17.drawPolygon(p);
        g17.fillPolygon(p);
        Graphics g18 = field20.getGraphics();
        g18.setColor(new Color(255, 250, 250));
        g18.drawPolygon(p);
        g18.fillPolygon(p);
        g18.setColor(black);
        for(int i=1;i<6;i++){
            g18.drawOval(10, y-50*i, 50, 50);
        g18.fillOval(10,y-50*i,50,50);
        }
        Graphics g19 = field21.getGraphics();
        g19.setColor(new Color(65, 42, 42));
        g19.drawPolygon(p);
        g19.fillPolygon(p);
        Graphics g20 = field22.getGraphics();
        g20.setColor(new Color(255, 250, 250));
        g20.drawPolygon(p);
        g20.fillPolygon(p);
        Graphics g21 = field23.getGraphics();
        g21.setColor(new Color(65, 42, 42));
        g21.drawPolygon(p);
        g21.fillPolygon(p);
        Graphics g22 = field24.getGraphics();
        g22.setColor(new Color(255, 250, 250));
        g22.drawPolygon(p);
        g22.fillPolygon(p);
        Graphics g23 = field25.getGraphics();
        g23.setColor(new Color(65, 42, 42));
        g23.drawPolygon(p);
        g23.fillPolygon(p);
        g23.setColor(new Color(255,0,0));
        for(int i=1;i<3;i++){
        g23.drawOval(10, y-55*i, 50, 50);
        g23.fillOval(10,y-55*i,50,50); 
        }      
        jButton1.setVisible(false);
        Graphics g24 = jPanel26.getGraphics();
        int x5 = jPanel26.getWidth();
        int y5 = jPanel26.getHeight();
        g24.setColor(new Color(205, 133, 63));
        g24.draw3DRect(0, 0, x5 / 2, y5, false);
        g24.fill3DRect(0, 0, x5 / 2, y5, false);
        g24.setColor(new Color(160, 82, 45));
        g24.draw3DRect(x5 / 4, y5 / 6, (x5) / 4, y5 / 6, false);
        g24.fill3DRect(x5 / 4, y5 / 6, (x5) / 4, y5 / 6, false);
        g24.setColor(new Color(205, 133, 63));
        g24.draw3DRect(x5 / 2, 0, (x5) / 2, y5, false);
        g24.fill3DRect(x5 / 2, 0, (x5) / 2, y5, false);
        g24.setColor(black);
        g24.drawLine(x5 / 2, 0, x5 / 2, y5);
        g24.setColor(new Color(160, 82, 45));
        g24.draw3DRect(x5 / 2, y5 / 6, x5 / 2, y5 / 6, false);
        g24.fill3DRect(x5 / 2, y5 / 6, x5 / 4, y5 / 6, false);
        g24.draw3DRect(x5 / 2, y5 * 4 / 6, x5 / 4, y5 / 6, false);
        g24.fill3DRect(x5 / 2, y5 * 4 / 6, x5 / 4, y5 / 6, false);
        g24.fill3DRect(x5 / 4, y5 * 4 / 6, x5 / 4, y5 / 6, false);
        g24.setColor(black);
        g24.drawOval(x5 / 4 + 15, y5 / 6 + 5, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 15, y5 / 6 + 5, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 15, y5 / 6 + 80, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 15, y5 / 6 + 80, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 60, y5 / 6 + 80, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 60, y5 / 6 + 80, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 60, y5 / 6 + 5, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 60, y5 / 6 + 5, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 60, y5 * 4 / 6 + 5, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 60, y5 * 4 / 6 + 5, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 60, y5 * 4 / 6 + 80, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 60, y5 * 4 / 6 + 80, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 15, y5 * 4 / 6 + 5, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 15, y5 * 4 / 6 + 5, y5 / 70, y5 / 70);
        g24.drawOval(x5 / 4 + 15, y5 * 4 / 6 + 80, y5 / 70, y5 / 70);
        g24.fillOval(x5 / 4 + 15, y5 * 4 / 6 + 80, y5 / 70, y5 / 70);
        jButton1.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        roll.setEnabled(false);
        Random rand = new Random();
        int dice1 = rand.nextInt(6) + 1;
        //System.out.println("Dice 1 : "+ dice1);
        ImageIcon image = new ImageIcon("C:\\Users\\Sava\\Downloads\\BackGammon (4)\\BackGammon\\src\\backgammon\\120px-Dice-1.png");
        ImageIcon image2 = new ImageIcon("C:\\Users\\Sava\\Downloads\\BackGammon (4)\\BackGammon\\src\\backgammon\\120px-Dice-2.png");
        ImageIcon image3 = new ImageIcon("C:\\Users\\Sava\\Downloads\\BackGammon (4)\\BackGammon\\src\\backgammon\\120px-Dice-3.png");
        ImageIcon image4 = new ImageIcon("C:\\Users\\Sava\\Downloads\\BackGammon (4)\\BackGammon\\src\\backgammon\\120px-Dice-4.png");
        ImageIcon image5 = new ImageIcon("C:\\Users\\Sava\\Downloads\\BackGammon (4)\\BackGammon\\src\\backgammon\\120px-Dice-5.png");
        ImageIcon image6 = new ImageIcon("C:\\Users\\Sava\\Downloads\\BackGammon (4)\\BackGammon\\src\\backgammon\\120px-Dice-6.png");
        int dice2 = rand.nextInt(6) + 1;
        // if(dice1==1){
        //Photo.setIcon(image);
        //}
        switch (dice1) {
            case 1:
                photo3.setIcon(image);
                break;
            case 2:
                photo3.setIcon(image2);
                break;
            case 3:
                photo3.setIcon(image3);
                break;
            case 4:
                photo3.setIcon(image4);
                break;
            case 5:
                photo3.setIcon(image5);
                break;
            case 6:
                photo3.setIcon(image6);
                break;
        }
        switch (dice2) {
            case 1:
                photo2.setIcon(image);
                break;
            case 2:
                photo2.setIcon(image2);
                break;
            case 3:
                photo2.setIcon(image3);
                break;
            case 4:
                photo2.setIcon(image4);
                break;
            case 5:
                photo2.setIcon(image5);
                break;
            case 6:
                photo2.setIcon(image6);
                break;

        }
//photo2.setIcon(image);
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        roll.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void field1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field1MouseClicked
//ArrayList<Stack<String>> board;
        Board obj= new Board();
       Stone obj1 = new Stone();
    //  Board.board;
  //   SetGet obj=new SetGet();
  //board obj=new board();
  
  
  //obj1.Black;
  //obj.position(board);
 obj.getBoard().get(0).pop();
        System.out.println(obj.getBoard().get(0));
         System.out.println(String.valueOf(obj1.Black));
        
            Graphics g11 = field1.getGraphics();
    //    g11.setColor(new Color(255, 250, 250));
     //   g11.drawPolygon(x1, y1, 3);
        //g11.setColor(new Color(255, 250, 250));
     //   g11.fillPolygon(p1);
    //    g11.setColor(black);
   //     g11.drawOval(10, 0, 50, 50);
   //     g11.fillOval(10,0,50,50);
    //    g11.drawOval(10, 50, 50, 50);
     //   g11.fillOval(10,50,50,50);
          g11.clearRect(10, 50, 50, 50);
          g11.setColor(new Color(255,250,250));
          g11.fillRect(10, 50, 50, 50);
    }//GEN-LAST:event_field1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Board obj=new Board();
       // System.out.println(obj.position(ArrayList<Stack<String>>ar));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //Graphics g=jPanel1.getGraphics();
                new NewJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel field1;
    private javax.swing.JPanel field10;
    private javax.swing.JPanel field11;
    private javax.swing.JPanel field12;
    private javax.swing.JPanel field13;
    private javax.swing.JPanel field14;
    private javax.swing.JPanel field15;
    private javax.swing.JPanel field16;
    private javax.swing.JPanel field17;
    private javax.swing.JPanel field18;
    private javax.swing.JPanel field19;
    private javax.swing.JPanel field2;
    private javax.swing.JPanel field20;
    private javax.swing.JPanel field21;
    private javax.swing.JPanel field22;
    private javax.swing.JPanel field23;
    private javax.swing.JPanel field24;
    private javax.swing.JPanel field25;
    private javax.swing.JPanel field3;
    private javax.swing.JPanel field4;
    private javax.swing.JPanel field5;
    private javax.swing.JPanel field6;
    private javax.swing.JPanel field7;
    private javax.swing.JPanel field9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JLabel photo2;
    private javax.swing.JLabel photo3;
    private javax.swing.JButton roll;
    // End of variables declaration//GEN-END:variables
}
